name: LeetCode Sync

on:
  schedule:
       # Runs daily at 11:45 PM IST (18:15 UTC)           
    - cron: "15 18 * * *"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.HUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.CSRFTOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: "solutions"
          verbose: true
